name: 'Babylon Alphanet version'
description: 'Get Babylon Alphanet version'
inputs:
  is_prerelease:
    description: "Is prerelease?"
    required: true
  github_event:
    description: "Github Event"
    required: true
  commit_sha:
    description: "Github commit sha"
    required: false
  release_tag:
    description: "Release version"
    required: false
outputs:
  babylon_alphanet_version:
    description: "Babylon Alphanet version"
    value: ${{ steps.get_version.outputs.babylon_alphanet_version }}
runs:
  using: "composite"
  steps:
    - id: get_version
      run: |
          GH_EVENT_NAME="${{ inputs.github_event }}"
          IS_PRERELEASE="${{ inputs.is_prerelease }}"
          COMMIT_SHA="${{ inputs.commit_sha }}"
          if [[ ! -z $IS_PRERELEASE ]] ;then
            RELEASE_VERSION="rc-${{ inputs.release_tag }}"
          elif [[ ! -z $GH_EVENT_NAME ]] && [[ "$GH_EVENT_NAME" == "release" ]] ;then
            RELEASE_VERSION="${{ inputs.release_tag }}"
          else
            RELEASE_VERSION="${{ github.sha }}"
          fi
          echo "Tag $RELEASE_VERSION"
          echo "::set-output name=babylon_alphanet_version::$RELEASE_VERSION"
      shell: bash