name: Alphanet Wallet Extension SDK build/publish

on:
  push:
    paths:
      - "alphanet-walletextension-sdk/**"
  release:
    types: [published]

jobs:
  build_alphanet_wallet_extension_sdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./alphanet-walletextension-sdk

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Use Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: "18.x"
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Running lint
        run: yarn lint

      - name: Running tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Prepare artifact
        run: rm -rf node_modules e2e lib sandbox

      - id: get_version
        name: Get babylon alphanet version
        uses: ./.github/actions/get-version
        with:
          github_event: ${{ github.event_name }}
          commit_sha: ${{ github.sha }}
          release_tag: ${{ github.event.release.tag_name }}

      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: alphanet-walletextension-sdk-${{ steps.get_version.outputs.babylon_alphanet_version }}
          path: alphanet-walletextension-sdk

      - name: Update package.json version
        if: github.event_name == 'release'
        uses: jossef/action-set-json-field@2a0f7d953b580b828717daf4de7fafc7e4135e97
        with:
          file: ./alphanet-walletextension-sdk/package.json
          field: version
          value: ${{ steps.get_version.outputs.babylon_alphanet_version }}

      - name: Publish alphanet wallet extension sdk to npm
        if: github.event_name == 'release'
        run: |
          npm config set access public
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


