name: Publish Gateway SDK

on:
  release:
    types: [published]
jobs:
  publish-gateway-sdk-npmjs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gateway-api-v0/typescript-sdk

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cat $NPM_CONFIG_USERCONFIG
      - name: Publish alphanet-gateway-sdk
        run: |
          yarn
          yarn build

      - id: get_version
        name: Get babylon alphanet version
        uses: ./.github/actions/get-version
        with:
          github_event: ${{ github.event_name }}
          commit_sha: ${{ github.sha }}
          release_tag: ${{ github.event.release.tag_name }}

      - name: Update package.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: ./gateway-api-v0/typescript-sdk/package.json
          field: version
          value: ${{ steps.get_version.outputs.babylon_alphanet_version }}

      - run: |
          npm config set access public
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
